[package]
name = "ism"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
env_logger = "0.11.6"
axum = "0.8.1"
tokio = {version = "1.42.0", features = ["full"]}
tower = "0.5.2"
config = "0.15.4"
serde = "1.0.217"
scylla = "0.15.1"
async-trait = "0.1.84"

[features]