name: 'Check Source Branch'
on:
  pull_request:
    branches:
      - main
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is development
        if: github.head_ref != 'development'
        run: |
          echo "ERROR: You can only merge to main from the development branch."
          exit 1